### ISSUE TITLE
ModuleNotFoundError

### ISSUE THREAD

**Issue by Emilza07** [bitagoras/PyPadPlusPlus#7]
Hi, I use Python 3.10, but cannot set it to work with PyPadPlusPlus :
When I try to use pyPadExecute or pyPadExecuteFix it's give me this error:

```
Traceback (most recent call last):
  File "C:\Program Files\Notepad++\plugins\PythonScript\scripts\plugins\config\PythonScript\scripts\pyPadExecuteFix.py", line 7, in <module>
    try: Npp.pypad != None
NameError: name 'Npp' is not defined

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Program Files\Notepad++\plugins\PythonScript\scripts\plugins\config\PythonScript\scripts\pyPadExecuteFix.py", line 8, in <module>
    except: from pyPadStart import *
ModuleNotFoundError: No module named 'pyPadStart'
```
IDK why it's showing that, I set the pythonPath correct.
so why?

**Comment by Emilza07** [comment]
Ok, I reinstalled, now it's 
`Traceback (most recent call last):
  File "C:\Program Files\Notepad++\plugins\PythonScript\scripts\PyPadPlusPlus-1.3.0\pyPadExecute.py", line 8, in <module>
    except: from pyPadStart import *
ImportError: No module named pyPadStart`

**Comment by bitagoras** [comment]
Yes, this undo Ctrl + z

**Comment by Emilza07** [comment]
Should I use this version? `Npp8.1_32bit_PyPadPlusPlus1.3.0_PythonScript3.0.7.zip`
if yes, in what folder hould I put it? in program files, or in users?

**Comment by bitagoras** [comment]
It should work in any folder.
